agent: win_openssh: use appropriate syscalls
 * use os.listdir() instead of os.path.exists(), because on windows the
   latter uses CreateFileW() and the pipe cannot be reopened unless the
   server calls DisconnectNamedPipe()

 * retry when open() raises Errno 22 which means that the server has not
   called DisconnectNamedPipe() yet

 * use os.{open,read,write,close}() because self._pipe.read() raises
   IOError: [Errno 0] on Python 2

follow-up to ploxiln/paramiko-ng#134